-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  customer_first_name TEXT NOT NULL,
  customer_last_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  shipping_county TEXT NOT NULL,
  shipping_town TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  shipping_instructions TEXT,
  payment_method TEXT NOT NULL,
  payment_status TEXT DEFAULT 'pending',
  delivery_zone TEXT NOT NULL,
  delivery_price INTEGER DEFAULT 0,
  delivery_status TEXT DEFAULT 'pending',
  subtotal INTEGER NOT NULL,
  discount INTEGER DEFAULT 0,
  total INTEGER NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL,
  product_name TEXT NOT NULL,
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  selected_size TEXT NOT NULL,
  selected_color TEXT NOT NULL,
  color_hex TEXT,
  image TEXT
);

-- Enable Row Level Security
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Create policies (allow public insert, authenticated read/write)
CREATE POLICY "Enable all access for authenticated users" ON orders
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Enable all access for authenticated users" ON order_items
  FOR ALL USING (auth.role() = 'authenticated');

-- Or for public access (use with caution)
CREATE POLICY "Allow public insert" ON orders
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public insert" ON order_items
  FOR INSERT WITH CHECK (true);

-- Create index for faster searches
CREATE INDEX idx_orders_phone ON orders(customer_phone);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created ON orders(created_at DESC);

-- Enable Realtime for orders
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
ALTER PUBLICATION supabase_realtime ADD TABLE order_items;

-- ============================================
-- NEWSLETTER SUBSCRIBERS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  confirmed_at TIMESTAMP WITH TIME ZONE,
  confirmed BOOLEAN DEFAULT FALSE,
  unsubscribed_at TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'subscribed', 'unsubscribed'))
);

-- Enable Row Level Security for newsletter_subscribers
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- Allow public insert (anyone can subscribe)
CREATE POLICY "Allow public insert for newsletter" ON newsletter_subscribers
  FOR INSERT WITH CHECK (true);

-- Allow authenticated users to read (admin view)
CREATE POLICY "Allow authenticated read for newsletter" ON newsletter_subscribers
  FOR SELECT USING (auth.role() = 'authenticated');

-- Enable Realtime for newsletter subscribers
ALTER PUBLICATION supabase_realtime ADD TABLE newsletter_subscribers;

-- Create index for faster email lookups
CREATE INDEX idx_newsletter_email ON newsletter_subscribers(email);
CREATE INDEX idx_newsletter_status ON newsletter_subscribers(status);
