-- ============================================
-- COMPLETE ORDERS SCHEMA FOR MAISH FASHION SHOP
-- Run this entire SQL in Supabase SQL Editor
-- ============================================

-- Create orders table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  order_number TEXT UNIQUE NOT NULL,
  customer_first_name TEXT NOT NULL,
  customer_last_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  shipping_county TEXT NOT NULL,
  shipping_town TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  shipping_instructions TEXT,
  payment_method TEXT NOT NULL,
  payment_status TEXT DEFAULT 'pending',
  delivery_zone TEXT NOT NULL,
  delivery_price INTEGER DEFAULT 0,
  delivery_status TEXT DEFAULT 'pending',
  subtotal INTEGER NOT NULL,
  discount INTEGER DEFAULT 0,
  total INTEGER NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create order_items table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL,
  product_name TEXT NOT NULL,
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  selected_size TEXT NOT NULL,
  selected_color TEXT NOT NULL,
  color_hex TEXT,
  image TEXT
);

-- Enable Row Level Security
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for orders
CREATE POLICY "Public Insert" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "User View Own" ON orders FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "User Update Own" ON orders FOR UPDATE USING (user_id = auth.uid());

-- Create RLS policies for order_items
CREATE POLICY "Public Insert Items" ON order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "User View Own Items" ON order_items FOR SELECT USING (order_id IN (SELECT id FROM orders WHERE user_id = auth.uid()));

-- Create indexes
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_phone ON orders(customer_phone);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created ON orders(created_at DESC);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
ALTER PUBLICATION supabase_realtime ADD TABLE order_items;
