-- ============================================
-- NEWSLETTER SUBSCRIBERS TABLE
-- ============================================

-- Create newsletter subscribers table
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  confirmed_at TIMESTAMP WITH TIME ZONE,
  confirmed BOOLEAN DEFAULT FALSE,
  unsubscribed_at TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'subscribed', 'unsubscribed'))
);

-- Enable Row Level Security for newsletter_subscribers
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- Allow public insert (anyone can subscribe)
CREATE POLICY "Allow public insert for newsletter" ON newsletter_subscribers
  FOR INSERT WITH CHECK (true);

-- Allow authenticated users to read (admin view)
CREATE POLICY "Allow authenticated read for newsletter" ON newsletter_subscribers
  FOR SELECT USING (auth.role() = 'authenticated');

-- Enable Realtime for newsletter subscribers
ALTER PUBLICATION supabase_realtime ADD TABLE newsletter_subscribers;

-- Create index for faster email lookups
CREATE INDEX IF NOT EXISTS idx_newsletter_email ON newsletter_subscribers(email);
CREATE INDEX IF NOT EXISTS idx_newsletter_status ON newsletter_subscribers(status);
